#!/bin/bash


set -e

function echo_log {
	DATE='date +%Y/%m/%d:%H:%M:%S'
	echo `$DATE`" $1"
}

initfile=/opt/icinga2/init.done

# update to latest snapshot packages
echo_log "Fetching latest icinga* snapshot packages."
{
  yum update --enablerepo=icinga-snapshot-builds -y icinga2 icingacli nrpe xinetd
  yum clean all
} &> /dev/null

echo_log "Validating the icinga2 configuration first."
#if ! icinga2 daemon -C; then
	#echo_log "Icinga 2 config validation failed. Stopping the container."
	#exit 0
#fi


if [ ! -f "${initfile}" ]; then
        echo_log "Enabling icinga2 features."
        # enable icinga2 features if not already there
#        icinga2 feature enable command
         icinga2 feature disable notification

        rm /etc/icinga2/conf.d/app.conf
        rm /etc/icinga2/conf.d/commands.conf
        rm /etc/icinga2/conf.d/downtimes.conf
        rm /etc/icinga2/conf.d/groups.conf
        rm /etc/icinga2/conf.d/hosts.conf
        rm /etc/icinga2/conf.d/notifications.conf
        rm /etc/icinga2/conf.d/satellite.conf
        rm /etc/icinga2/conf.d/services.conf
        rm /etc/icinga2/conf.d/templates.conf
        rm /etc/icinga2/conf.d/timeperiods.conf
        rm /etc/icinga2/conf.d/users.conf
        echo "constant DNODE = \"$IEND\"" >> /etc/icinga2/constants.conf
        echo "constant DZONE = \"$IZONE\"" >> /etc/icinga2/constants.conf

        echo_log "Enabling icingaweb2 modules."
        if [[ -L /etc/icingaweb2/enabledModules/monitoring ]]; then echo "Symlink for /etc/icingaweb2/enabledModules/monitoring exists already...skipping"; else ln -s /usr/share/icingaweb2/modules/monitoring /etc/icingaweb2/enabledModules/monitoring; fi

        touch ${initfile}
fi




echo_log "Starting Supervisor. CTRL-C will stop the container."
/usr/bin/supervisord -c /etc/supervisord.conf >> /dev/null
