#!/bin/bash


set -e

function echo_log {
	DATE='date +%Y/%m/%d:%H:%M:%S'
	echo `$DATE`" $1"
}

initfile=/opt/icinga2/init.done

# update to latest snapshot packages
echo_log "Fetching latest icinga* snapshot packages."
{
  yum update --enablerepo=icinga-snapshot-builds -y icinga2 icingacli nrpe xinetd
  yum clean all
} &> /dev/null

echo_log "Validating the icinga2 configuration first."
#if ! icinga2 daemon -C; then
	#echo_log "Icinga 2 config validation failed. Stopping the container."
	#exit 0
#fi


if [ ! -f "${initfile}" ]; then
        echo_log "Enabling icinga2 features."
        # enable icinga2 features if not already there
#        icinga2 feature enable command
         icinga2 feature disable notification

        rm /etc/icinga2/conf.d/app.conf
        rm /etc/icinga2/conf.d/commands.conf
        rm /etc/icinga2/conf.d/downtimes.conf
        rm /etc/icinga2/conf.d/groups.conf
        rm /etc/icinga2/conf.d/hosts.conf
        rm /etc/icinga2/conf.d/notifications.conf
        rm /etc/icinga2/conf.d/satellite.conf
        rm /etc/icinga2/conf.d/services.conf
        rm /etc/icinga2/conf.d/templates.conf
        rm /etc/icinga2/conf.d/timeperiods.conf
        rm /etc/icinga2/conf.d/users.conf
        echo "const DNODE = \"$IEND\"" >> /etc/icinga2/constants.conf
        sed -i -e 's/^.* NodeName = .*/ /gi' /etc/icinga2/constants.conf;
        echo "const NodeName = \"$IEND\"" >> /etc/icinga2/constants.conf
        echo "const DZONE = \"$IZONE\"" >> /etc/icinga2/constants.conf


        if [ "${ICLUSTER}" == "Y" ]; then
           echo "const DNODE2 = \"$IEND2\"" >> /etc/icinga2/constants.conf
           sed -i -e 's/DNODE/DNODE, DNODE2/' /etc/icinga2/conf.d/sb.conf 

           cp /etc/icinga2/conf.d/sb-node2.TMP /etc/icinga2/conf.d/sb-node.conf
        fi

    
        cat /dev/null > /etc/icinga2/zones.conf

        #icinga2 pki new-cert --cn $IEND --key /etc/icinga2/pki/$IEND.key --csr /etc/icinga2/pki/$IEND.csr; \
        #icinga2 pki sign-csr --csr /etc/icinga2/pki/$IEND.csr --cert /etc/icinga2/pki/$IEND.crt;
        echo_log "Updating NRPE"
        cp /etc/nagios/nrpe.cfg /etc/nagios/nrpe.cfg.orig
        cat /etc/nagios/nrpe.cfg | grep -v 'nrpe_user' | grep -v 'nrpe_group' | grep -v 'allowed_hosts' | grep -v 'dont_blame_nrpe' >> /etc/nagios/nrpe.cfg.tmp
        mv /etc/nagios/nrpe.cfg.tmp /etc/nagios/nrpe.cfg

        echo "nrpe_user=nagios" >> /etc/nagios/nrpe.cfg
        echo "nrpe_group=nagios" >> /etc/nagios/nrpe.cfg
        echo "dont_blame_nrpe=1" >> /etc/nagios/nrpe.cfg


        echo_log "Enabling icingaweb2 modules."
        if [[ -L /etc/icingaweb2/enabledModules/monitoring ]]; then echo "Symlink for /etc/icingaweb2/enabledModules/monitoring exists already...skipping"; else ln -s /usr/share/icingaweb2/modules/monitoring /etc/icingaweb2/enabledModules/monitoring; fi

        cp /etc/icinga2/features-available/api.conf.checker /etc/icinga2/features-available/api.conf
        chown icinga:icinga /etc/icinga2/features-available
        chown icinga:icinga /etc/icinga2/features-available/api.conf

        chmod u+s /usr/lib64/icinga2/sbin/icinga2

        touch ${initfile}
fi


if ! icinga2 daemon -C; then
        echo_log "Icinga 2 config validation failed."
fi

chmod u+s /usr/lib64/nagios/plugins/*

echo_log "Starting Supervisor. CTRL-C will stop the container."
/usr/bin/supervisord -c /etc/supervisord.conf >> /dev/null
